# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinderLikeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderLikeApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Koloda'
  pod 'RxSwift', '~> 5'
  pod 'IQKeyboardManagerSwift'
  pod 'RxCocoa', '~> 5'
  pod 'LTMorphingLabel'
end


